### ISSUE TITLE
ExtractTextPlugin

### ISSUE THREAD

**Issue by lukasholzer** [xsbear/hash-assets-webpack-plugin#1]
Is it possible to get the hashes of the files that are processed with the ExtractTextPlugin?
Would be nice for extracted stylesheets.

Regards Lukas

**Comment by xsbear** [comment]
Yes, it supports getting hashes of all chunks, include chunks which generated by ExtractTextPlugin. It also supports use `contenthash` which specified by ExtractTextPlugin, so css files won't change hash without any modify when only entry files has change.  Just try it.
